CREATE TABLE IF NOT EXISTS `fornecedores` (
  `id` char(36) NOT NULL,
  `codigo` varchar(40) NOT NULL DEFAULT '',
  `tipo_pessoa` int NOT NULL DEFAULT 2,
  `nome_fantasia` varchar(150) NOT NULL DEFAULT '',
  `razao_social` varchar(180) NOT NULL DEFAULT '',
  `cnpj` varchar(30) NOT NULL DEFAULT '',
  `inscricao_estadual` varchar(30) NOT NULL DEFAULT '',
  `inscricao_municipal` varchar(30) NOT NULL DEFAULT '',
  `telefone` varchar(30) NOT NULL DEFAULT '',
  `celular` varchar(30) NOT NULL DEFAULT '',
  `whatsapp` varchar(30) NOT NULL DEFAULT '',
  `email` varchar(180) NOT NULL DEFAULT '',
  `site` varchar(180) NOT NULL DEFAULT '',
  `cep` varchar(20) NOT NULL DEFAULT '',
  `endereco` varchar(220) NOT NULL DEFAULT '',
  `numero` varchar(20) NOT NULL DEFAULT '',
  `complemento` varchar(120) NOT NULL DEFAULT '',
  `bairro` varchar(120) NOT NULL DEFAULT '',
  `cidade` varchar(120) NOT NULL DEFAULT '',
  `estado` varchar(2) NOT NULL DEFAULT '',
  `contato_responsavel` varchar(150) NOT NULL DEFAULT '',
  `cargo_contato` varchar(120) NOT NULL DEFAULT '',
  `prazo_pagamento_padrao` int NOT NULL DEFAULT 0,
  `limite_compra` decimal(18,2) NOT NULL DEFAULT 0,
  `observacoes` varchar(500) NOT NULL DEFAULT '',
  `ativo` tinyint(1) NOT NULL DEFAULT 1,
  `criado_em` datetime(6) NOT NULL,
  `atualizado_em` datetime(6) NULL,
  PRIMARY KEY (`id`),
  KEY `IX_fornecedores_nome_fantasia` (`nome_fantasia`),
  KEY `IX_fornecedores_razao_social` (`razao_social`),
  KEY `IX_fornecedores_cnpj` (`cnpj`),
  KEY `IX_fornecedores_telefone` (`telefone`),
  KEY `IX_fornecedores_whatsapp` (`whatsapp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
